CUDA_VISIBLE_DEVICES=6 python train_online_kangaroo.py \
    --model_path /data/wangzhichao/projects/MMDuet2/ckpt/MMDuet2_ckpt \
    --data_path /data/wangzhichao/projects/SSD_test/AAAA/data/annotations/adapter/all.jsonl \
    --outdir /data/wangzhichao/projects/SSD_test/AAAA/adapter_checkpoints/online_12_resume_from_29_klce \
    --exit_layer 12 \
    --device cuda:0 \
    --lr 3e-6 \
    --num_epochs 5 \
    --adapter_path /data/wangzhichao/projects/SSD_test/AAAA/adapter_checkpoints/offline_12_mrope_kl+ce_re/epochs/epoch029_top10.8581_draft11.0000_longdraft11.0000_overlap0.8190_loss0.3840 \
    --num_warmup_steps 30 \
    --grad_clip 0.5 \
    --speculative_steps 6 \
    --threshold 0.0 \
    --post_mismatch_weight 0.0 \
    --hidden_loss_weight 0.0 \
    --ce_weight 0.5 \
    --kl_weight 1.0 \
    --kl_temperature 1.0 \
    --no_reply_keep_ratio 0.0
